### 알고리즘 비교
- [1] RF + LDA 
- [2] RF + PCA
- [3] RF 

## [1] Recognizing hand-written digits + LDA + RF

In [0]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

## 데이터 로드
digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))
X_train, X_test, y_train, y_test = train_test_split(data, digits.target, test_size=0.5, shuffle=False)


## 데이터 변환
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=32)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(64, 10 - 1) = 9 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [0]:
import numpy as np 
import pandas as pd 
from sklearn import datasets 
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))
X_train, X_test, y_train, y_test = train_test_split(data, digits.target, test_size = 0.5, shuffle = False)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA 
lda = LDA(n_components = 32)
X_train = lda.fit_transform(X_train,y_train)
X_test = lda.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(64, 10 - 1) = 9 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [0]:

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth = 2, random_state= 0)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)



/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:

## 데이터 평가
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test,y_pred)

print(cm)
print(accuracy_score(y_test, y_pred))

[[86  0  0  0  1  0  0  0  0  1]
 [ 0  0 55  8  9  0  0  0 16  3]
 [ 0  0 72 12  0  2  0  0  0  0]
 [ 0  0 10 69  0  6  0  0  3  3]
 [ 2  0  0  0 80  1  2  1  0  6]
 [ 1  0  1  1  0 82  5  1  0  0]
 [ 0  0  1  0 11  2 77  0  0  0]
 [ 0  0 11  1  5  7  0 62  0  3]
 [ 0  0 14  1  4  8  1  0 44 16]
 [ 5  0  4  6  0  1  0  1 10 65]]
0.7085650723025584


## [2] Recognizing hand-written digits + PCA + RF

In [0]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split


## 데이터 로드
digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))
X_train, X_test, y_train, y_test = train_test_split(data, digits.target, test_size=0.5, shuffle=False)

## 데이터 변환
from sklearn.decomposition import PCA
pca = PCA(n_components=32)
X_train = pca.fit_transform(X_train, y_train)
X_test = pca.fit_transform(X_test)



In [0]:
## 데이터 분류기 학습 및 테스트

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:

## 평가

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[ 5  0  0 68  0  0  0 12  1  2]
 [ 2  0  2  2  2  4 59  1  4 15]
 [21  0  1  8 25  0 25  4  0  2]
 [62  0  6  4  1  3 12  0  1  2]
 [ 5  0  0  1  1  7  3 62  6  7]
 [ 1  0  0  1  7 70  7  2  1  2]
 [ 0  0  0  9  0  0  0 78  2  2]
 [14  0  0  0 38  0 37  0  0  0]
 [ 7  0  5 19 10  2 28  4 13  0]
 [33  0  4 27  1  7  3  0  9  8]]
Accuracy0.11345939933259176


## [3] Recognizing hand-written digits + RF

In [0]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

## 데이터 로드
digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))
X_train, X_test, y_train, y_test = train_test_split(data, digits.target, test_size=0.5, shuffle=False)



In [0]:
## 데이터 분류기 학습 및 테스트

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:

## 데이터 평가
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[87  0  0  0  1  0  0  0  0  0]
 [ 0 40  6  6  7  3  0 13  5 11]
 [ 1  0 63 15  0  0  0  2  2  3]
 [ 2  2  0 73  0  0  1  9  2  2]
 [ 7  0  0  0 78  0  2  5  0  0]
 [ 2  1  0 39 14 21  1  4  1  8]
 [ 2  1  0  1  0  0 86  0  1  0]
 [ 0  0  0  0 10  1  0 78  0  0]
 [ 1 10 18  8  5  1  2 14 27  2]
 [ 0  0  0 11  2  1  0  4  1 73]]
Accuracy0.696329254727475
